name: isar_flutter_libs
description: Flutter binaries for the Isar Database. Needs to be included for Flutter apps.
version: 2.2.1
repository: https://github.com/isar/isar
homepage: https://isar.dev

environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar:
    git: # temporary fix until we migrate to flutter 2.10
      url: https://github.com/NizamSaidin/isar.git
      path: packages/isar

flutter:
  plugin:
    platforms:
      android:
        package: dev.isar.isar_flutter_libs
        pluginClass: IsarFlutterLibsPlugin
      ios:
        pluginClass: IsarFlutterLibsPlugin
      macos:
        pluginClass: IsarFlutterLibsPlugin
      linux:
        pluginClass: IsarFlutterLibsPlugin
      windows:
        pluginClass: IsarFlutterLibsPlugin
